### ISSUE TITLE
Bugs and Todo 

### ISSUE THREAD

**Issue by realoriginal** [realoriginal/reflectivepotato#1]
Hopefully within the next week, I could fix

 - [x] When calling the payload, the process itself doesn't appear to impersonate the handle of the system token, and thus requiring the loading incognito. Lovely. Maybe https://msdn.microsoft.com/en-us/library/windows/desktop/aa446617(v=vs.85).aspx is the solution?

 - [x] Perhaps instead of using CreateThread, SetThreadToken, & ResumeThread, I could rely on SetThreadToken to elevate the current process to SYSTEM? (UNTESTED, just a theory) In combination with DuplicateTokenEx. Or maybe just substitute DuplicateTokenEx and use that token for SetThreadToken. :man_shrugging: 

 - [x] The Meterpreter module that hasnt been posted strangely results in the loss of the shell. Not ..entirely sure what could possibly be causing it. At the moment, I have to load the listener via `exploit/multi/handler`, and set `DisablePayloadHandler` to `true` to force the shell to load. Quite..weird.

 - [x] The Proxy socket is left binding to the interface once shellcode has been invoked. Intead of return, I'll attempt to just perform `break;` & allow it to cleanup from there

**Comment by realoriginal** [comment]
Tested on Windows 7 x64 SP1, and Windows 2008 R2 SP1

**Comment by realoriginal** [comment]
Maybe also later adapt cross protocol NTLMv2 reflection? https://github.com/CoreSecurity/impacket/issues/451

**Comment by realoriginal** [comment]
Most of the bugs listed at the top have been fixed through one work around or another. Either way, I will revist in the future if need be to fix any bugs or possibly later incorporate features from Juicy Potato.
